---
permalink: online-help-96-97/reference_windows_window.html 
sidebar: sidebar 
keywords: storage, virtual, machine, svm, cluster, online, help, user, tab, command, buttons, group 
summary: 您可以使用Windows視窗來維護叢集上每個儲存虛擬機器（SVM）的本機Windows使用者和群組清單。您可以使用本機Windows使用者和群組進行驗證和名稱對應。 
---
= 系統管理程式的Windows視窗ONTAP -更新版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 經典版的《經典版》（ONTAP 僅適用於更新版本的版本）來使用Windows視窗。Windows視窗可協助您維護叢集上每個儲存虛擬機器（SVM）的本機Windows使用者和群組清單。您可以使用本機Windows使用者和群組進行驗證和名稱對應。



== 使用者索引標籤

您可以使用「使用者」索引標籤來檢視SVM本機的Windows使用者。



== 命令按鈕

* *建立*
+
開啟「建立使用者」對話方塊、可讓您建立本機Windows使用者帳戶、以便透過SMB連線授權存取SVM中所含的資料。

* *編輯*
+
開啟「編輯使用者」對話方塊、可讓您編輯本機Windows使用者內容、例如群組成員資格和完整名稱。您也可以啟用或停用使用者帳戶。

* *刪除*
+
開啟「刪除使用者」對話方塊、可讓您在不再需要SVM時、從SVM刪除本機Windows使用者帳戶。

* *加入群組*
+
開啟「新增群組」對話方塊、可讓您將群組成員資格指派給使用者帳戶（如果您希望使用者具有與該群組相關的權限）。

* *設定密碼*
+
開啟「重設密碼」對話方塊、可讓您重設Windows本機使用者的密碼。例如、如果密碼洩漏或使用者忘記密碼、您可能會想要重設密碼。

* *重新命名*
+
開啟「重新命名使用者」對話方塊、可讓您重新命名本機Windows使用者帳戶、以便更容易識別。

* *重新整理*
+
更新視窗中的資訊。





== 使用者清單

* *名稱*
+
顯示本機使用者的名稱。

* *全名*
+
顯示本機使用者的完整名稱。

* *停用帳戶*
+
顯示本機使用者帳戶是啟用還是停用。

* *說明*
+
顯示本機使用者的說明。





== 使用者詳細資料區域

* *群組*
+
顯示使用者所屬的群組清單。





== 群組索引標籤

您可以使用群組索引標籤來新增、編輯或刪除SVM本機的Windows群組。



== 命令按鈕

* *建立*
+
開啟「建立群組」對話方塊、可讓您建立本機Windows群組、以便透過SMB連線來授權存取SVM中所含的資料。

* *編輯*
+
開啟「編輯群組」對話方塊、可讓您編輯本機Windows群組內容、例如指派給群組的權限和群組說明。

* *刪除*
+
開啟刪除群組對話方塊、可讓您在不再需要時、從SVM刪除本機Windows群組。

* *新增成員*
+
開啟「新增成員」對話方塊、可讓您將本機或Active Directory使用者或Active Directory群組新增至本機Windows群組。

* *重新命名*
+
開啟「重新命名群組」對話方塊、可讓您重新命名本機Windows群組、以便更容易識別。

* *重新整理*
+
更新視窗中的資訊。





== 群組清單

* *名稱*
+
顯示本機群組的名稱。

* *說明*
+
顯示本機群組的說明。





== 群組詳細資料區域

* *權限*
+
顯示與所選群組相關的權限清單。

* *使用者*
+
顯示與所選群組相關聯的本機使用者清單。



*相關資訊*

xref:task_creating_local_user_group.adoc[建立本機Windows群組]

xref:task_editing_local_windows_group_properties.adoc[編輯本機Windows群組內容]

xref:task_adding_user_accounts_to_windows_local_group.adoc[新增使用者帳戶至Windows本機群組]

xref:task_renaming_local_windows_group.adoc[重新命名本機Windows群組]

xref:task_deleting_local_windows_group.adoc[刪除本機Windows群組]

xref:task_creating_local_windows_user_accounts.adoc[建立本機Windows使用者帳戶]

xref:task_editing_local_windows_user_properties.adoc[編輯本機Windows使用者內容]

xref:task_assigning_group_memberships_to_user_account.adoc[指派群組成員資格給使用者帳戶]

xref:task_renaming_local_windows_user.adoc[重新命名本機Windows使用者]

xref:task_changing_password_for_windows_local_users.adoc[重設Windows本機使用者的密碼]

xref:task_deleting_local_windows_user_account.adoc[刪除本機Windows使用者帳戶]
