---
permalink: nas-multiprotocol-config/reference_where_to_find_additional_information.html 
sidebar: sidebar 
keywords: test, cifs, nfs, client, access, perform, advanced, configuration, san, access, procotol, root, volume, svm, comprehensive, report, achieve, goal, where to find additional information 
summary: 在成功測試CIFS和NFS用戶端存取之後、您可以執行進階CIFS和NFS組態或新增SAN存取。傳輸協定存取完成時、您應該保護SVM的根Volume。我們提供全方位的內容和技術報告、協助您達成這些目標。 
---
= 何處可找到其他資訊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在成功測試CIFS和NFS用戶端存取之後、您可以執行進階CIFS和NFS組態或新增SAN存取。傳輸協定存取完成時、您應該保護SVM的根Volume。我們提供全方位的內容與技術報告、協助您達成這些目標。



== CIFS/SMB組態

您可以使用下列資訊和技術報告進一步設定CIFS存取：

* https://docs.netapp.com/us-en/ontap/smb-admin/index.html["CIFS管理"^]
+
說明如何使用CIFS/SMB傳輸協定來設定及管理檔案存取。

* http://www.netapp.com/us/media/tr-4191.pdf["NetApp技術報告4191：叢集Data ONTAP 式更新的最佳實務做法指南8.2 Windows檔案服務"^]
+
提供SMB實作與其他Windows檔案服務功能的簡短概述、並提供ONTAP 有關的建議與基本疑難排解資訊。

* http://www.netapp.com/us/media/tr-3740.pdf["NetApp技術報告3740：SMB 2 Next-Generation CIFS Protocol in Data ONTAP"^]
+
介紹SMB 2的功能、組態詳細資料、以及ONTAP 其在功能方面的實作。





== NFS組態

您可以使用下列資訊和技術報告進一步設定NFS存取：

* https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS管理"^]
+
說明如何使用NFS傳輸協定來設定及管理檔案存取。

* http://www.netapp.com/us/media/tr-4067.pdf["NetApp技術報告4067：NFS最佳實務與實作"^]
+
可做為NFSv3和NFSv3作業指南、提供ONTAP 關於以NFSv3為焦點的各種作業系統的概述。

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["NetApp技術報告4668：名稱服務最佳實務做法"^]
+
提供完整的最佳實務做法、限制、建議及考量清單、以供設定LDAP、NIS、DNS及本機使用者與群組檔案進行驗證。

* https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf["NetApp技術報告4616：ONTAP NFS Kerberos in Some with Microsoft Active Directory"^]
* https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf["NetApp技術報告4835：如何在ONTAP 功能方面設定LDAP"^]
* http://www.netapp.com/us/media/tr-3580.pdf["NetApp技術報告3580：NFSv4增強功能與最佳實務做法指南Data ONTAP -實作"^]
+
說明在掛接到執行ONTAP 此功能的系統上、在AIX、Linux或Solaris用戶端上實作NFSv4元件時應遵循的最佳實務做法。





== 根Volume保護

在SVM上設定傳輸協定之後、您應確保其根Volume受到保護：

* https://docs.netapp.com/us-en/ontap/data-protection/index.html["資料保護"^]
+
說明如何建立負載共用鏡像來保護SVM根磁碟區、這是NetApp啟用NAS的SVM最佳實務做法。同時也說明如何從負載共用鏡像中提升SVM根磁碟區、以快速從磁碟區故障或損失中恢復


